#:kivy 2.3.0
<MyPopup>:
    BoxLayout:
        orientation: 'vertical'

        # Label untuk pertanyaan
        Label:
            text: "Apakah Anda yakin?"

        # Layout untuk tombol
        BoxLayout:
            size_hint_y: 0.3

            Button:
                text: "Ya"
                on_press: root.on_yes()
            

            Button:
                text: "Tidak"
                on_press: root.on_no()